#!/usr/bin/env bash
# Claude Code adapter: writes .claude/ wiring that points at .senior-mode/.
#   .claude/settings.json      hooks (canonical format, native) + permissions + plugins
#   .claude/rules/*.md         core rules, stack rules override same-layer core rules
#   .claude/agents/*.md        reviewers, native frontmatter
#   .claude/commands/*.md      commands, native frontmatter
#   .claude/workflows/         multi-agent audit (Claude Code Workflow tool)
# CLAUDE.md at the root is written by install.sh (it imports AGENTS.md).
set -u
. "$(dirname "${BASH_SOURCE[0]}")/../_lib.sh"
SM_TARGET="$(cd "$1" && pwd)"

{
  cat <<'HDR'
{
  "$schema": "https://json.schemastore.org/claude-code-settings.json",
  "$comment": "Generated by senior-mode (adapters/claude). Hooks live in .senior-mode/hooks and fail open. Re-run install.sh after editing the core; edit this file directly only for project-local extras (or use settings.local.json).",
  "permissions": {
    "allow": [
      "Bash(git status:*)", "Bash(git log:*)", "Bash(git diff:*)", "Bash(git show:*)",
      "Bash(git branch --show-current)", "Bash(git branch -a)", "Bash(git fetch:*)",
      "Bash(git worktree list:*)", "Bash(git stash list:*)", "Bash(git remote -v)",
      "Bash(bash .senior-mode/hooks/test-checklist.sh)",
      "Bash(bash .senior-mode/hooks/session-registry.sh list)",
      "Bash(bash .senior-mode/stacks/detect.sh:*)"
    ]
  },
HDR
  sm_hooks_json '$CLAUDE_PROJECT_DIR' yes | sed '1d; $d'   # inner "hooks": {...} without the outer braces
  cat <<'FTR'
,
  "enabledPlugins": {
    "code-review@claude-plugins-official": true,
    "code-simplifier@claude-plugins-official": true,
    "security-guidance@claude-plugins-official": true,
    "commit-commands@claude-plugins-official": true,
    "playwright@claude-plugins-official": true
  }
}
FTR
} | sm_put "$SM_TARGET/.claude/settings.json"

while IFS= read -r f; do [ -n "$f" ] && sm_copy "$f" "$SM_TARGET/.claude/rules/$(basename "$f")"; done < <(sm_rule_files)
for f in "$SM_KIT"/core/reviewers/*.md; do sm_copy "$f" "$SM_TARGET/.claude/agents/$(basename "$f")"; done
for f in "$SM_KIT"/core/commands/*.md; do sm_copy "$f" "$SM_TARGET/.claude/commands/$(basename "$f")"; done
if [ -n "$SM_STACK" ] && [ -d "$SM_KIT/stacks/$SM_STACK/commands" ]; then
  for f in "$SM_KIT/stacks/$SM_STACK/commands"/*.md; do [ -f "$f" ] && sm_copy "$f" "$SM_TARGET/.claude/commands/$(basename "$f")"; done
fi
for f in "$SM_KIT"/adapters/claude/workflows/*.mjs; do [ -f "$f" ] && sm_copy "$f" "$SM_TARGET/.claude/workflows/$(basename "$f")"; done
