#!/usr/bin/env bash
# OpenCode adapter.
#   opencode.json               instructions -> the rules; declarative bash permission gates
#   .opencode/plugins/senior-mode.ts  tool.execute.before runs the canonical guards (throw = deny);
#                               the system-prompt transform injects the BEFORE checklist
#   .opencode/commands/*.md     commands (format is compatible: description, $ARGUMENTS)
#   .opencode/agents/*.md       reviewers as subagents (edit denied for read-only reviewers)
#   .agents/skills/*/SKILL.md   commands as Agent Skills as well
# OpenCode reads AGENTS.md natively (root, nested lazily). permission.ask is
# not wired in OpenCode's plugin runtime (open issue), so the plugin denies by
# throwing inside tool.execute.before, which the docs specify.
set -u
. "$(dirname "${BASH_SOURCE[0]}")/../_lib.sh"
SM_TARGET="$(cd "$1" && pwd)"

cat <<'EOF' | sm_put "$SM_TARGET/opencode.json"
{
  "$schema": "https://opencode.ai/config.json",
  "$comment": "Generated by senior-mode (adapters/opencode). Rules load via instructions; the plugin in .opencode/plugins runs the canonical hooks.",
  "instructions": [".senior-mode/rules/*.md"],
  "permission": {
    "bash": {
      "git push*": "ask",
      "git push --force*": "deny",
      "git reset --hard*": "ask"
    }
  }
}
EOF

cat <<'EOF' | sm_put "$SM_TARGET/.opencode/plugins/senior-mode.ts"
// Generated by senior-mode (adapters/opencode). Runs the canonical hook
// scripts in .senior-mode/hooks against OpenCode's tool calls and turns.
//
//   tool.execute.before (bash)  -> session-tree-guard, pre-commit-audit,
//                                  pre-push-checklist, exit-code-mask-guard;
//                                  a "deny" decision throws, which OpenCode
//                                  reports to the model as a failed tool call.
//   tool.execute.after (edit)   -> post-edit-format
//   system prompt transform     -> the BEFORE checklist, once per turn
//
// The hooks speak the Claude Code / Codex JSON contract; this file only
// builds that payload and reads the decision back. Fail-open: any error in
// the shell-out allows the call.
import type { Plugin } from "@opencode-ai/plugin";

const GUARDS = [
  "session-tree-guard.sh",
  "pre-commit-audit.sh",
  "pre-push-checklist.sh",
  "exit-code-mask-guard.sh",
];

export const SeniorMode: Plugin = async ({ $, directory }) => {
  const hooks = `${directory}/.senior-mode/hooks`;
  const env = { ...process.env, SENIOR_MODE_PROJECT_DIR: directory, CLAUDE_PROJECT_DIR: directory };

  async function run(script: string, payload: object, arg = ""): Promise<string> {
    try {
      // Bun's shell exposes stdin as a readonly property, not a method; the
      // only way to feed it is a redirect. An empty ${arg} would become an
      // empty argv slot under Bun quoting, so it is interpolated only when set.
      const body = new Response(JSON.stringify(payload));
      const cmd = arg
        ? $`bash ${hooks}/${script} ${arg} < ${body}`
        : $`bash ${hooks}/${script} < ${body}`;
      const out = await cmd.env(env).cwd(directory).quiet().nothrow();
      return out.stdout.toString();
    } catch {
      return "";
    }
  }
  const field = (json: string, key: string): string => {
    const m = json.replace(/\n/g, " ").match(new RegExp(`"${key}"\\s*:\\s*"((?:[^"\\\\]|\\\\.)*)"`));
    return m ? m[1].replace(/\\n/g, "\n").replace(/\\"/g, '"') : "";
  };

  return {
    "tool.execute.before": async (input, output) => {
      if (input.tool !== "bash") return;
      const command = String(output.args?.command ?? "");
      const payload = {
        session_id: input.sessionID,
        hook_event_name: "PreToolUse",
        tool_name: "Bash",
        cwd: directory,
        tool_input: { command },
      };
      for (const g of GUARDS) {
        const out = await run(g, payload);
        if (/"permissionDecision"\s*:\s*"deny"/.test(out)) {
          throw new Error(field(out, "permissionDecisionReason") || `blocked by ${g}`);
        }
      }
    },
    "tool.execute.after": async (input) => {
      if (input.tool !== "edit" && input.tool !== "write") return;
      const file_path = String((input.args as any)?.filePath ?? (input.args as any)?.file_path ?? "");
      if (!file_path) return;
      await run("post-edit-format.sh", {
        session_id: input.sessionID,
        hook_event_name: "PostToolUse",
        tool_name: "Write",
        tool_input: { file_path },
      });
    },
    "experimental.chat.system.transform": async (input, output) => {
      const out = await run("senior-check-before.sh", {
        session_id: input.sessionID ?? "opencode",
        hook_event_name: "UserPromptSubmit",
        prompt: "",
      });
      const ctx = field(out, "additionalContext");
      if (ctx) output.system.push(ctx);
    },
  };
};
EOF

for f in "$SM_KIT"/core/commands/*.md; do sm_copy "$f" "$SM_TARGET/.opencode/commands/$(basename "$f")"; done
if [ -n "$SM_STACK" ] && [ -d "$SM_KIT/stacks/$SM_STACK/commands" ]; then
  for f in "$SM_KIT/stacks/$SM_STACK/commands"/*.md; do [ -f "$f" ] && sm_copy "$f" "$SM_TARGET/.opencode/commands/$(basename "$f")"; done
fi

for f in "$SM_KIT"/core/reviewers/*.md; do
  name=$(sm_fm_get "$f" name); [ -n "$name" ] || name=$(basename "$f" .md)
  desc=$(sm_fm_get "$f" description)
  tools=$(sm_fm_get "$f" tools)
  {
    printf -- '---\ndescription: %s\nmode: subagent\n' "$desc"
    case "$tools" in *Edit*|*Write*) ;; *) printf 'permission:\n  edit: deny\n' ;; esac
    printf -- '---\n'
    sm_body "$f"
  } | sm_put "$SM_TARGET/.opencode/agents/$name.md"
done

for f in "$SM_KIT"/core/commands/*.md; do sm_skill_from_command "$f" "$SM_TARGET/.agents/skills"; done
