#!/usr/bin/env bash
# GitHub Copilot adapter. Hooks are supported on two surfaces: the Copilot
# CLI and the Copilot cloud agent (VS Code is not one; the "VS Code
# compatible" name below is a payload format, not a surface).
#   .github/hooks/senior-mode.json         hooks. PascalCase event names select
#                                          Copilot's VS Code compatible payload
#                                          format, whose snake_case fields and
#                                          Claude tool names ARE the canonical
#                                          contract. The "command" key is
#                                          documented as copied to both bash and
#                                          powershell, so hooks run on Windows
#                                          too (a bare "bash" key never did).
#   .github/copilot-instructions.md        points at AGENTS.md (Copilot reads AGENTS.md natively too)
#   .github/instructions/*.instructions.md rules with applyTo globs
#   .github/agents/*.agent.md              reviewers as custom agents
#   .agents/skills/*/SKILL.md              commands as Agent Skills (Copilot reads .agents/skills)
# What cannot be mirrored: userPromptSubmitted command hooks have their
# output dropped by documentation, so the BEFORE check cannot inject there
# and is carried by AGENTS.md instead; only the registry touch (a pure side
# effect) stays wired on that event. PreToolUse denies go through
# copilot-shim.sh because Copilot reads a TOP-LEVEL permissionDecision, not
# the nested hookSpecificOutput. Copilot's preToolUse is fail-closed on a
# non-zero exit; the shim and the canonical hooks always exit 0, so a broken
# hook allows rather than blocks.
set -u
. "$(dirname "${BASH_SOURCE[0]}")/../_lib.sh"
SM_TARGET="$(cd "$1" && pwd)"

H=".senior-mode/hooks"
cat <<EOF | sm_put "$SM_TARGET/.github/hooks/senior-mode.json"
{
  "version": 1,
  "\$comment": "Generated by senior-mode (adapters/copilot). Hooks live in .senior-mode/hooks. Commands are repo-relative; Copilot runs hooks from the repo root (cloud: /workspace). command is copied to bash and powershell; Windows needs bash (Git Bash) on PATH.",
  "hooks": {
    "SessionStart": [
      { "hooks": [ { "type": "command", "command": "bash \\"$H/session-registry.sh\\" register", "timeoutSec": 15 } ] }
    ],
    "SessionEnd": [
      { "hooks": [ { "type": "command", "command": "bash \\"$H/session-registry.sh\\" unregister", "timeoutSec": 15 } ] }
    ],
    "UserPromptSubmit": [
      { "hooks": [ { "type": "command", "command": "bash \\"$H/session-registry.sh\\" touch", "timeoutSec": 15 } ] }
    ],
    "PreToolUse": [
      { "matcher": "Bash", "hooks": [ { "type": "command", "command": "bash \\".senior-mode/adapters/copilot-shim.sh\\" guard \\"$H/session-tree-guard.sh\\" \\"$H/pre-commit-audit.sh\\" \\"$H/pre-push-checklist.sh\\" \\"$H/exit-code-mask-guard.sh\\"", "timeoutSec": 20 } ] }
    ],
    "PostToolUse": [
      { "matcher": "Write|Edit", "hooks": [ { "type": "command", "command": "bash \\"$H/post-edit-format.sh\\"", "timeoutSec": 30 } ] }
    ],
    "Stop": [
      { "hooks": [ { "type": "command", "command": "bash \\"$H/senior-check-after.sh\\"", "timeoutSec": 5 } ] }
    ]
  }
}
EOF

{
  cat <<'EOF'
# Copilot instructions

Read `AGENTS.md` at the repository root first: it is the source of truth
for how to work in this repo (senior-mode). Everything below is a pointer.

- Doctrine: `ENGINEERING-PRINCIPLES.md` (never/always lists, LOC budget, verification craft).
- Briefing standard: `PROMPT-STANDARD.md`.
- Path-scoped rules: `.github/instructions/*.instructions.md` (generated from `.senior-mode/rules/`).
- Reviewers: `.github/agents/*.agent.md`. Procedures: `.agents/skills/*/SKILL.md`.
- Hooks: `.github/hooks/senior-mode.json` (commit/push gates, senior checks).
EOF
} | sm_put "$SM_TARGET/.github/copilot-instructions.md"

while IFS= read -r f; do
  [ -n "$f" ] || continue
  name=$(basename "$f" .md)
  globs=$(sm_rule_globs "$f"); [ -n "$globs" ] || globs="**"
  {
    printf -- '---\napplyTo: "%s"\n---\n' "$globs"
    printf '<!-- Generated from .senior-mode/rules/%s.md by senior-mode; edit the source, then re-run install.sh. -->\n' "$name"
    sm_body "$f"
  } | sm_put "$SM_TARGET/.github/instructions/$name.instructions.md"
done < <(sm_rule_files)

for f in "$SM_KIT"/core/reviewers/*.md; do
  name=$(sm_fm_get "$f" name); [ -n "$name" ] || name=$(basename "$f" .md)
  desc=$(sm_fm_get "$f" description)
  tools=$(sm_fm_get "$f" tools)
  case "$tools" in *Edit*|*Write*) tl='["read", "search", "edit", "execute"]' ;; *) tl='["read", "search", "execute"]' ;; esac
  {
    printf -- '---\nname: %s\ndescription: %s\ntools: %s\n---\n' "$name" "$desc" "$tl"
    sm_body "$f"
  } | sm_put "$SM_TARGET/.github/agents/$name.agent.md"
done

for f in "$SM_KIT"/core/commands/*.md; do sm_skill_from_command "$f" "$SM_TARGET/.agents/skills"; done
if [ -n "$SM_STACK" ] && [ -d "$SM_KIT/stacks/$SM_STACK/commands" ]; then
  for f in "$SM_KIT/stacks/$SM_STACK/commands"/*.md; do [ -f "$f" ] && sm_skill_from_command "$f" "$SM_TARGET/.agents/skills"; done
fi
