#!/usr/bin/env bash
# GitHub Copilot adapter (CLI, cloud agent, VS Code agent mode).
#   .github/hooks/senior-mode.json         hooks, PascalCase events (Claude-compatible payload:
#                                          tool_input / hookSpecificOutput); the CLI accepts these
#                                          and VS Code converts them. Cloud honors the "bash" field only.
#   .github/copilot-instructions.md        points at AGENTS.md (Copilot reads AGENTS.md natively too)
#   .github/instructions/*.instructions.md rules with applyTo globs
#   .github/agents/*.agent.md              reviewers as custom agents
#   .agents/skills/*/SKILL.md              commands as Agent Skills (Copilot reads .agents/skills)
# Note: Copilot's preToolUse is fail-closed on a non-zero exit; the canonical
# hooks always exit 0, so a broken hook allows rather than blocks.
set -u
. "$(dirname "${BASH_SOURCE[0]}")/../_lib.sh"
SM_TARGET="$(cd "$1" && pwd)"

{
  printf '{\n  "version": 1,\n  "$comment": "Generated by senior-mode (adapters/copilot). Hooks live in .senior-mode/hooks. Commands are repo-relative; Copilot runs hooks from the repo root (cloud: /workspace).",\n'
  sm_hooks_json '.' yes timeoutSec 1 bash | sed '1d'
} | sed 's|bash \\"\./\.senior-mode|bash \\".senior-mode|g' | sm_put "$SM_TARGET/.github/hooks/senior-mode.json"

{
  cat <<'EOF'
# Copilot instructions

Read `AGENTS.md` at the repository root first: it is the source of truth
for how to work in this repo (senior-mode). Everything below is a pointer.

- Doctrine: `ENGINEERING-PRINCIPLES.md` (never/always lists, LOC budget, verification craft).
- Briefing standard: `PROMPT-STANDARD.md`.
- Path-scoped rules: `.github/instructions/*.instructions.md` (generated from `.senior-mode/rules/`).
- Reviewers: `.github/agents/*.agent.md`. Procedures: `.agents/skills/*/SKILL.md`.
- Hooks: `.github/hooks/senior-mode.json` (commit/push gates, senior checks).
EOF
} | sm_put "$SM_TARGET/.github/copilot-instructions.md"

while IFS= read -r f; do
  [ -n "$f" ] || continue
  name=$(basename "$f" .md)
  globs=$(sm_rule_globs "$f"); [ -n "$globs" ] || globs="**"
  {
    printf -- '---\napplyTo: "%s"\n---\n' "$globs"
    printf '<!-- Generated from .senior-mode/rules/%s.md by senior-mode; edit the source, then re-run install.sh. -->\n' "$name"
    sm_body "$f"
  } | sm_put "$SM_TARGET/.github/instructions/$name.instructions.md"
done < <(sm_rule_files)

for f in "$SM_KIT"/core/reviewers/*.md; do
  name=$(sm_fm_get "$f" name); [ -n "$name" ] || name=$(basename "$f" .md)
  desc=$(sm_fm_get "$f" description)
  tools=$(sm_fm_get "$f" tools)
  case "$tools" in *Edit*|*Write*) tl='["read", "search", "edit", "execute"]' ;; *) tl='["read", "search", "execute"]' ;; esac
  {
    printf -- '---\nname: %s\ndescription: %s\ntools: %s\n---\n' "$name" "$desc" "$tl"
    sm_body "$f"
  } | sm_put "$SM_TARGET/.github/agents/$name.agent.md"
done

for f in "$SM_KIT"/core/commands/*.md; do sm_skill_from_command "$f" "$SM_TARGET/.agents/skills"; done
if [ -n "$SM_STACK" ] && [ -d "$SM_KIT/stacks/$SM_STACK/commands" ]; then
  for f in "$SM_KIT/stacks/$SM_STACK/commands"/*.md; do [ -f "$f" ] && sm_skill_from_command "$f" "$SM_TARGET/.agents/skills"; done
fi
