#!/usr/bin/env bash
# Cursor adapter (editor agent and the `agent` CLI).
#   .cursor/hooks.json        v1 hooks routed through .senior-mode/adapters/cursor-shim.sh
#   .cursor/rules/*.mdc       rules with description + globs (agent-requested / auto-attached)
#   .cursor/agents/*.md       reviewers as subagents (readonly for read-only reviewers)
#   .agents/skills/*/SKILL.md commands as Agent Skills (Cursor's preferred replacement for commands)
# Cursor reads AGENTS.md natively (root and nested) and exports CLAUDE_PROJECT_DIR
# as an alias, so the canonical hooks locate the repo unchanged.
# What cannot be mirrored: beforeSubmitPrompt cannot inject context, so the
# BEFORE checklist arrives once per session via sessionStart; the AFTER check
# uses stop -> followup_message. The shim maps Cursor's loop_count to
# stop_hook_active, so the canonical backstop in senior-check-after.sh caps
# the loop at one follow-up per block. No loop_limit here: Cursor counts it
# per conversation, which silenced the after-check from turn 2 onward.
set -u
. "$(dirname "${BASH_SOURCE[0]}")/../_lib.sh"
SM_TARGET="$(cd "$1" && pwd)"

R='$CURSOR_PROJECT_DIR'
S="bash \\\"$R/.senior-mode/adapters/cursor-shim.sh\\\""
H="$R/.senior-mode/hooks"
cat <<EOF | sm_put "$SM_TARGET/.cursor/hooks.json"
{
  "version": 1,
  "\$comment": "Generated by senior-mode (adapters/cursor). Each entry runs the shim, which translates Cursor's payload to the canonical hook contract and back. Fail-open.",
  "hooks": {
    "sessionStart": [
      { "command": "$S session \\"$H/session-registry.sh:register\\" \\"$H/senior-check-before.sh\\"", "timeout": 15 }
    ],
    "sessionEnd": [
      { "command": "$S session \\"$H/session-registry.sh:unregister\\"", "timeout": 10 }
    ],
    "beforeSubmitPrompt": [
      { "command": "$S prompt \\"$H/session-registry.sh:touch\\" \\"$H/ultracode-advisor.sh\\"", "timeout": 10 }
    ],
    "beforeShellExecution": [
      { "command": "$S shell \\"$H/session-tree-guard.sh\\" \\"$H/pre-commit-audit.sh\\" \\"$H/pre-push-checklist.sh\\" \\"$H/exit-code-mask-guard.sh\\"", "timeout": 20 }
    ],
    "afterFileEdit": [
      { "command": "$S edit \\"$H/post-edit-format.sh\\"", "timeout": 30 }
    ],
    "stop": [
      { "command": "$S stop \\"$H/senior-check-after.sh\\"", "timeout": 5 }
    ]
  }
}
EOF

while IFS= read -r f; do
  [ -n "$f" ] || continue
  name=$(basename "$f" .md)
  desc=$(sm_first_line "$f")
  globs=$(sm_rule_globs "$f")
  {
    printf -- '---\ndescription: %s\n' "$desc"
    [ -n "$globs" ] && printf 'globs: %s\n' "$globs"
    printf 'alwaysApply: false\n---\n'
    printf '<!-- Generated from .senior-mode/rules/%s.md by senior-mode; edit the source, then re-run install.sh. -->\n' "$name"
    sm_body "$f"
  } | sm_put "$SM_TARGET/.cursor/rules/$name.mdc"
done < <(sm_rule_files)

for f in "$SM_KIT"/core/reviewers/*.md; do
  name=$(sm_fm_get "$f" name); [ -n "$name" ] || name=$(basename "$f" .md)
  desc=$(sm_fm_get "$f" description)
  tools=$(sm_fm_get "$f" tools)
  ro=true; case "$tools" in *Edit*|*Write*) ro=false ;; esac
  {
    printf -- '---\nname: %s\ndescription: %s\nmodel: inherit\nreadonly: %s\n---\n' "$name" "$desc" "$ro"
    sm_body "$f"
  } | sm_put "$SM_TARGET/.cursor/agents/$name.md"
done

for f in "$SM_KIT"/core/commands/*.md; do sm_skill_from_command "$f" "$SM_TARGET/.agents/skills"; done
if [ -n "$SM_STACK" ] && [ -d "$SM_KIT/stacks/$SM_STACK/commands" ]; then
  for f in "$SM_KIT/stacks/$SM_STACK/commands"/*.md; do [ -f "$f" ] && sm_skill_from_command "$f" "$SM_TARGET/.agents/skills"; done
fi
