#!/usr/bin/env bash
# Gemini CLI adapter.
#   .gemini/settings.json     context.fileName -> AGENTS.md + hooks routed through gemini-shim.sh
#   .gemini/commands/*.toml   commands ($ARGUMENTS -> {{args}})
#   .gemini/agents/*.md       reviewers as sub-agents (read-only tool list for read-only reviewers)
#   .agents/skills/*/SKILL.md commands as Agent Skills as well (Gemini reads .agents/skills)
# Gemini exports CLAUDE_PROJECT_DIR as an alias of GEMINI_PROJECT_DIR. Its stdin
# is already the canonical shape; the shim maps event names and stdout.
# Note (2026-06): Gemini CLI serves paid-API and Code Assist Standard/Enterprise
# users only; free-tier users were moved to Antigravity CLI.
set -u
. "$(dirname "${BASH_SOURCE[0]}")/../_lib.sh"
SM_TARGET="$(cd "$1" && pwd)"

R='$GEMINI_PROJECT_DIR'
S="bash \\\"$R/.senior-mode/adapters/gemini-shim.sh\\\""
H="$R/.senior-mode/hooks"
cat <<EOF | sm_put "$SM_TARGET/.gemini/settings.json"
{
  "\$comment": "Generated by senior-mode (adapters/gemini). context.fileName makes Gemini read AGENTS.md; hooks route through the shim in .senior-mode/adapters. Timeouts are milliseconds. Fail-open.",
  "context": { "fileName": ["AGENTS.md", "GEMINI.md"] },
  "hooks": {
    "SessionStart": [
      { "hooks": [ { "name": "senior-mode-session", "type": "command", "command": "$S SessionStart \\"$H/session-registry.sh:register\\"", "timeout": 15000 } ] }
    ],
    "SessionEnd": [
      { "hooks": [ { "name": "senior-mode-session-end", "type": "command", "command": "$S SessionEnd \\"$H/session-registry.sh:unregister\\"", "timeout": 10000 } ] }
    ],
    "BeforeAgent": [
      { "hooks": [ { "name": "senior-mode-before", "type": "command", "command": "$S BeforeAgent \\"$H/session-registry.sh:touch\\" \\"$H/senior-check-before.sh\\" \\"$H/ultracode-advisor.sh\\"", "timeout": 10000 } ] }
    ],
    "BeforeTool": [
      { "matcher": "run_shell_command", "hooks": [ { "name": "senior-mode-guards", "type": "command", "command": "$S BeforeTool \\"$H/session-tree-guard.sh\\" \\"$H/pre-commit-audit.sh\\" \\"$H/pre-push-checklist.sh\\" \\"$H/exit-code-mask-guard.sh\\"", "timeout": 20000 } ] }
    ],
    "AfterTool": [
      { "matcher": "write_file|replace", "hooks": [ { "name": "senior-mode-format", "type": "command", "command": "$S AfterTool \\"$H/post-edit-format.sh\\"", "timeout": 30000 } ] }
    ],
    "AfterAgent": [
      { "hooks": [ { "name": "senior-mode-after", "type": "command", "command": "$S AfterAgent \\"$H/senior-check-after.sh\\"", "timeout": 5000 } ] }
    ]
  }
}
EOF

emit_toml_command() { # <command.md> <dest.toml>
  local src="$1" dest="$2" desc
  desc=$(sm_fm_get "$src" description)
  {
    printf '# Generated from core/commands/%s by senior-mode; edit the source, then re-run install.sh.\n' "$(basename "$src")"
    printf 'description = "%s"\n' "$(printf '%s' "$desc" | sed 's/\\/\\\\/g; s/"/\\"/g')"
    printf "prompt = '''\n"
    sm_body "$src" | sed "s/\\\$ARGUMENTS/{{args}}/g; s/'''/''\\\\''/g"
    printf "'''\n"
  } | sm_put "$dest"
}
for f in "$SM_KIT"/core/commands/*.md; do emit_toml_command "$f" "$SM_TARGET/.gemini/commands/$(basename "$f" .md).toml"; done
if [ -n "$SM_STACK" ] && [ -d "$SM_KIT/stacks/$SM_STACK/commands" ]; then
  for f in "$SM_KIT/stacks/$SM_STACK/commands"/*.md; do [ -f "$f" ] && emit_toml_command "$f" "$SM_TARGET/.gemini/commands/$(basename "$f" .md).toml"; done
fi

for f in "$SM_KIT"/core/reviewers/*.md; do
  name=$(sm_fm_get "$f" name); [ -n "$name" ] || name=$(basename "$f" .md)
  desc=$(sm_fm_get "$f" description)
  tools=$(sm_fm_get "$f" tools)
  case "$tools" in *Edit*|*Write*) tl='[read_file, read_many_files, glob, grep_search, list_directory, run_shell_command, write_file, replace]' ;; *) tl='[read_file, read_many_files, glob, grep_search, list_directory, run_shell_command]' ;; esac
  {
    printf -- '---\nname: %s\ndescription: %s\ntools: %s\n---\n' "$name" "$desc" "$tl"
    sm_body "$f"
  } | sm_put "$SM_TARGET/.gemini/agents/$name.md"
done

for f in "$SM_KIT"/core/commands/*.md; do sm_skill_from_command "$f" "$SM_TARGET/.agents/skills"; done
